### ISSUE TITLE
Not Working for Private Repo

### ISSUE THREAD

**Issue by sagarswamirao** [LeetPushExtension/LeetPush#54]

**Comment by mraduldubey** [comment]
Same - I dont even see a PUSH button anywhere. INstalled from chrome extension

**Comment by husamahmud** [comment]
> Same - I dont even see a PUSH button anywhere. INstalled from chrome extension

submit a solution first to see the push button :)

**Comment by husamahmud** [comment]
please give all permissions to your GitHub token so it can push to your private repo
