### ISSUE TITLE
Extension is not working properly.

### ISSUE THREAD

**Issue by Harshh18** [LeetPushExtension/LeetPush#77]
![image](https://github.com/user-attachments/assets/621e1da3-b719-4e99-8e85-8b8fd36bcf45)
I tried to upload the code to Github, but it's not working then I refresh my Leetcode and Github website and the push button from the leetcode was gone and the extension is not able to fetch my details also from the username.

**Comment by husamahmud** [comment]
- The extension button displayed when you submit a solution and it's correct 
- the username of your LeetCode account is `Harshhk` not `Harshh18`, please recheck it

**Comment by Harshh18** [comment]
You're right, but after re checking everything I try to push the code but it is not getting committed to my Github repo. I am pushing the code for problem no. 58 in my repo.
Actually, my token was expired and I regenerated the token again and after adding the new token it is not pushing my code in the repo.
[Repo link](https://github.com/Harshh18/Daily-DSA)

**Comment by Harshh18** [comment]
Hey, I'm still unable to figure out what's going wrong with my side. I have even generated a new token for the same but still the extension is not able to commit changes into my repository. It'd be great if someone hops in to help me with this.

**Comment by husamahmud** [comment]
can you provide me with your GitHub repo link?

**Comment by Harshh18** [comment]
https://github.com/Harshh18/Daily-DSA

Here it is
