### ISSUE TITLE
Pushing solutions changes README file and repo info.

### ISSUE THREAD

**Issue by YusufAbdelaziz** [LeetPushExtension/LeetPush#80]
I don't know whether it's a bug or not, but the README file and repo info are changing whenever a solution is pushed. I think that's annoying for anyone who wants to add a table for tracking his progress in a README file.

**Comment by YusufAbdelaziz** [comment]
The name of the repo is already on the commit message.

**Comment by husamahmud** [comment]
Okay lemme see what I can do, thanks ❤️
