### ISSUE TITLE
cannot edit repo url

### ISSUE THREAD

**Issue by sj098** [LeetPushExtension/LeetPush#82]
Hi,

I need to edit my repo url but the edit button only lets me enter my leetcode username. Also, which url should I use for the repo url?

**Comment by ammarGamal123** [comment]
Hi @sj098,

You can actually edit your repo URL. Here's how:

1- Select the "Edit" button:

<img width="585" alt="Github-Resposne-Edit-Button" src="https://github.com/user-attachments/assets/6cd50bea-2200-4eca-bfe0-17b1eef13897">

2- After clicking "Edit," this screen will be displayed, allowing you to modify your repo URL as needed:

<img width="244" alt="Github-Screen" src="https://github.com/user-attachments/assets/1142b9de-38dd-4429-ba5b-75490bf95398">
