### ISSUE TITLE
Where is "dist/index.html" file ? 

### ISSUE THREAD

**Issue by juheesvt** [LeetPushExtension/LeetPush#86]
![image](https://github.com/user-attachments/assets/c2309438-06a7-4116-ab43-2f761dd5a3dc)

**I wanted to change the commit message**, 
so I downloaded the code from the repository locally and uploaded it directly using the Chrome extension developer mode.

However, an error message appears saying that it cannot be loaded because the **dist/index.html file does not exist**. 
How can I solve this problem?

**Comment by husamahmud** [comment]
try `npm run build` in the popup dir
