### ISSUE TITLE
Issue with Token Renewal for LeetPush App

### ISSUE THREAD

**Issue by Zvimarmor** [LeetPushExtension/LeetPush#96]
I’ve been using the LeetPush app to push my LeetCode solutions to my GitHub account, and it has been incredibly helpful. However, I recently encountered an issue: the GitHub token for the app expired, and I couldn't find any way to renew or update the token within the app.

Despite generating a new token on GitHub, there seems to be no option to link it back to the LeetPush app. This has made it impossible for me to continue using the app as intended.

I would greatly appreciate it if you could address this issue or provide guidance on how to resolve it.

**Comment by husamahmud** [comment]
I think this will be helpful to generate a new GitHub access token [here](https://github.com/orgs/community/discussions/74701#discussioncomment-7515072), after that, you can click the `Edit` button next to the `Push` button for the LeetPush extension and renew it, and you are ready to go.
